apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote
spec:
  vars:
    - name: repoURL
      value: https://github.com/bergtobias/homelab-infra
    - name: branch
      value: main
    - name: image
      value: ghcr.io/bergtobias/bergtobias
    - name: openpr
      value: "false"
  steps:
    # Clone the Git repository that contains the Kustomize configuration
    # to the ./src directory.
    - uses: git-clone
      config:
        repoURL: ${{ vars.repoURL }}
        checkout:
          - branch: ${{ vars.branch }}
            path: ./src
    - uses: kustomize-set-image
      # Update the image in the Kustomize configuration located at ./env/<stage>

      # in the repository.
      as: update-image
      config:
        path: ./src/apps/bergtobias/overlays/${{ ctx.stage }}
        images:
          - image: ${{ vars.image }}
            tag: ${{ imageFrom( vars.image ).Tag }}
    - uses: git-commit
      # Commit the changes to the Git repository.

      as: commit
      config:
        path: ./src
        message: ${{ task.outputs['update-image'].commitMessage }}
    - uses: git-push
      # Push the changes to the Git repository.

      if: ${{ vars.openpr != 'true' }}
      config:
        path: ./src
    - uses: git-push
      # Push the changes to a newly created branch in the Git repository.

      if: ${{ vars.openpr == 'true' }}
      as: push
      config:
        path: ./src
        generateTargetBranch: true
    - uses: git-open-pr
      # Open a pull request to merge the changes into the main branch.

      as: open-pr
      if: ${{ vars.openpr == 'true' }}
      config:
        repoURL: ${{ vars.repoURL }}
        createTargetBranch: true
        sourceBranch: ${{ task.outputs.push.branch }}
        targetBranch: ${{ vars.branch }}
    - uses: git-wait-for-pr
      # Wait for the pull request to be merged.

      as: wait-for-pr
      if: ${{ vars.openpr == 'true' }}
      config:
        repoURL: ${{ vars.repoURL }}
        prNumber: ${{ task.outputs['open-pr'].prNumber }}
        # If you have an Argo CD Application that should be synced after the Git
    - uses: argocd-update
      # repository is updated, uncomment the following lines and specify the

      # app name.
      config:
        apps:
          - name: bergtobias-${{ ctx.stage }}
            sources:
              - repoURL: ${{ vars.repoURL }}
