apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
data:
  TZ: "Europe/London"
  WEBPASSWORD: "changeme"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: pihole
          image: pihole/pihole:latest
          ports:
            - containerPort: 5353 # Change DNS port to avoid conflict
              hostPort: 5353
              protocol: UDP
            - containerPort: 5353 # Same change for TCP
              hostPort: 5353
              protocol: TCP
            - containerPort: 8080 # Pi-hole web UI on a non-conflicting port
              hostPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: pihole-config
          volumeMounts:
            - mountPath: /etc/pihole
              name: config
            - mountPath: /etc/dnsmasq.d
              name: dnsmasq
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pihole-config-pvc
        - name: dnsmasq
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
spec:
  selector:
    app: pihole
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
