apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: eggman
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: openpr
              value: "false"
