apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: eggman
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
