apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-overlay-generator
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/bergtobias/homelab-infra" # Replace with your Git repository URL
        revision: "main" # Branch to track
        directories:
          - path: "apps/*/overlays/*" # Match overlays under each app recursively
  template:
    metadata:
      name: "{{path.basename}}" # App name based on overlay folder (env)
    spec:
      project: default # Change if needed
      source:
        repoURL: "https://github.com/bergtobias/homelab-infra"
        targetRevision: "main"
        path: "{{path}}" # Full path to the overlay
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{path[1]}}-{{path.basename}}" # namespace = appname-env
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
