apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main-applicationset
spec:
  generators:
    - git:
        repoURL: "https://github.com/bergtobias/homelab-infra"
        revision: HEAD
        directories:
          - path: "apps/"
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: "https://github.com/bergtobias/homelab-infra"
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "default"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
