apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset
spec:
  generators:
    - git:
        repoURL: "https://github.com/bergtobias/homelab-infra"
        revision: HEAD
        paths:
          - apps/*

  template:
    metadata:
      name: "{{path.basename}}" # This will resolve to app1, app2, etc.
    spec:
      project: default
      source:
        repoURL: "https://github.com/bergtobias/homelab-infra"
        targetRevision: HEAD
        path: "{{path}}" # This will resolve to apps/app1, apps/app2, etc.
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "default"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
