apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls
  namespace: default
spec:
  secretName: tls
  dnsNames:
    - "*.bergtobias.com"
    - "bergtobias.com"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
