apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-cert
  namespace: istio-system
spec:
  secretName: istio-gateway-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - bergtobias.com
