apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  dnsNames:
    - argo.bergtobias.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
