apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: prod-web
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
    - protocol: HTTPS
      hostname: "argocd.bergtobias.com"
      port: 443
      name: prod-web-gw
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTP
      hostname: "app.bergtobias.com"
      port: 80
      name: prod-tls-gw
      allowedRoutes:
        namespaces:
          from: All
