apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
    - protocol: https
      port: 433
      name: prod-web-gw
      allowedRoutes:
        namespaces:
          from: All
