apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
    - protocol: HTTP
      port: 80
      name: prod-web-gw
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS # Other possible value is `TLS`
      hostname: "argocd.bergtobias.com"
      port: 443
      tls:
        mode: Terminate # If protocol is `TLS`, `Passthrough` is a possible mode
        certificateRefs:
          - kind: Secret
            group: ""
            name: default-cert
