apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
    - port: 80
      protocol: HTTP
      name: http
