apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
    - port: 80
      protocol: HTTP
      hosts:
        - "*"
    - port: 443
      protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: istio-ingress-cert
      hosts:
        - "*"
