apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
    - name: wildcard-https
      protocol: HTTPS
      port: 443
      hostname: "*.bergtobias.com"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            group: ""
            name: bergtobias-com-cert
    - port: 80
      name: http
      protocol: HTTP
      hostname: "*.bergtobias.com"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        httpsRedirect: true # sends 301 redirect for http requests
