apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
  name: gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
    - protocol: HTTP
      port: 80
      name: prod-web-gw
      allowedRoutes:
        namespaces:
          from: All
