apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
    - protocol: http
      port: 80
      name: prod-web-gw
      allowedRoutes:
        namespaces:
          from: All
    - protocol: https
      port: 443
      name: prod-wtls-gw
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs: istio-ingress-cert
