apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tls-gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.bergtobias.com"
      tls:
        certificateRefs:
          - kind: Secret
            group: ""
            name: bergtobias-com-cert
