apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
    - protocol: HTTP
      port: 80
      name: http-prod-web-gw
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https-prod-web-gw
      tls:
        mode: SIMPLE
        credentialName: istio-ingress-cert # Replace with your certificate's secret name
      allowedRoutes:
        namespaces:
          from: All
