apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-charts
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: istio
            chart: base
            repoURL: https://istio-release.storage.googleapis.com/charts
            targetRevision: 1.18.2
            namespace: istio-system
            valuesFile: helm/istio/values.yaml
  template:
    metadata:
      name: "{{name}}"
    spec:
      project: default
      source:
        repoURL: "{{repoURL}}"
        targetRevision: "{{targetRevision}}"
        chart: "{{chart}}"
        helm:
          valueFiles:
            - "{{valuesFile}}"
      destination:
        namespace: "{{namespace}}"
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      createNamespace: true
