apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bootstrap-config
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - chart: vault
            name: vault
            repo: https://helm.releases.hashicorp.com
            revision: 0.27.0
            namespace: vault
            postInstall: true
          - chart: cert-manager
            name: cert-manager
            repo: https://charts.jetstack.io
            revision: v1.14.4
            namespace: cert-manager
            postInstall: false

  template:
    metadata:
      name: "{{.name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
      destination:
        namespace: "{{.namespace}}"
        server: https://kubernetes.default.svc
      project: default
  source:
    repoURL: "{{.repo}}"
    chart: "{{.chart}}"
    targetRevision: "{{.revision}}"
    helm:
      releaseName: "{{.name}}"
      parameters:
        - name: key
          value: value
