apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bootstrap-config
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - chart: vault
            name: vault
            repo: https://helm.releases.hashicorp.com
            revision: 0.27.0
            namespace: vault
            postInstall: true
  template:
    metadata:
      name: "{{.name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
      destination:
        namespace: "{{.namespace}}"
        server: https://kubernetes.default.svc
      project: default
  templatePatch: |
    spec:
      sources:
        - repoURL: '{{ .repo }}'
          chart: '{{ .chart }}'
          targetRevision: '{{ .revision }}'
          helm:
            valueFiles:
              - $values/helm/{{ .name }}/values.yaml
        - repoURL: https://github.com/bergtobias/homelab-infra.git
          targetRevision: HEAD
          ref: values
