apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bootstrap-config
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/your-repo/helm-charts.git
        revision: HEAD
        directories:
          - path: "charts/*"
  template:
    metadata:
      name: "{{.path.basename}}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
      destination:
        namespace: "{{.path.basename}}-namespace"
        server: https://kubernetes.default.svc
      project: default
      sources:
        - repoURL: "https://github.com/your-repo/helm-charts.git"
          chart: "{{ .path.basename }}"
          targetRevision: HEAD
          helm:
            valueFiles:
              - $values/helm/{{ .path.basename }}/values.yaml
        - repoURL: https://github.com/bergtobias/homelab-infra.git
          targetRevision: HEAD
          ref: values
  templatePatch: |
    spec:
      sources:
        - repoURL: '{{ .repo }}'
          chart: '{{ .chart }}'
          targetRevision: '{{ .revision }}'
          helm:
            valueFiles:
              - $values/helm/{{ .name }}/values.yaml
        - repoURL: https://github.com/bergtobias/homelab-infra.git
          targetRevision: HEAD
          ref: values
