apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-filter-redirect
spec:
  parentRefs:
    - name: gateway # Must match the Gateway name
      namespace: istio-system # Must match the Gateway namespace
  hostnames:
    - "*.bergtobias.com" # Must be consistent with your Gateway’s hostname(s) if you set any
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
