apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bergtobias/homelab-infra
    targetRevision: main
    path: helm/nginx-ingress
    helm:
      valueFiles:
        - https://github.com/bergtobias/homelab-infra/helm/ingress-nginx/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
