apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: "69.8.2" # Use the exact version
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - $values/helm-values/prometheus-values.yaml
          - $values/helm-values/grafana-values.yaml

    - repoURL:
      targetRevision: HEAD
      ref: values
      
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
