apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_GITOPS_REPO.git # Change to your GitOps repo
    targetRevision: main # Or specify a branch/tag
    path: helm-values # Path in your repo where the Helm values exist
    helm:
      valueFiles:
        - prometheus-values.yaml
        - grafana-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
