apiVersion: v1
kind: Service
metadata:
  name: sample-nginx-svc
  namespace: default
spec:
  selector:
    app: sample-nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
