apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-route
  namespace: eggman
spec:
  parentRefs:
    - name: gateway # Must match the Gateway name
      namespace: istio-system # Must match the Gateway namespace
  hostnames:
    - "*.bergtobias.com" # Must be consistent with your Gateway’s hostname(s) if you set any
  rules:
    - backendRefs:
        - name: eggman-svc # The Service receiving traffic
          port: 80
