apiVersion: v1
kind: Pod
metadata:
  name: vault-busybox-test-2
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "k8s-role"
    vault.hashicorp.com/agent-inject-secret-mysecret.txt: "secret/data/kv/secret"
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: vault-secrets
          mountPath: /vault/secrets
          readOnly: true
  volumes:
    - name: vault-secrets
      emptyDir: {}
