apiVersion: batch/v1
kind: Job
metadata:
  name: vault-k8s-auth-setup
  namespace: vault # <-- Correct namespace
spec:
  template:
    spec:
      serviceAccountName: vault
      containers:
        - name: vault
          image: hashicorp/vault:1.13.3 # <-- Fixed here
          command: ["/bin/sh", "-c"]
          args:
            - |
              vault auth enable kubernetes
              vault write auth/kubernetes/config \
                kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443" \
                kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
                token_reviewer_jwt=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          env:
            - name: VAULT_ADDR
              value: "http://vault.vault.svc.cluster.local:8200"
      restartPolicy: OnFailure
