apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: foo-route
spec:
  parentRefs:
    - name: example-gateway
  hostnames:
    - "foo.localhost"
  rules:
    - backendRefs:
        - name: app1
          port: 80
