apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app1
spec:
  parentRefs:
    - name: gateway
      namespace: istio-system
  hostnames:
    - app.bergtobias.com
  rules:
    - backendRefs:
        - name: app1
          port: 80
  tls:
    - hosts:
        - app.bergtobias.com
      secretName: argocd-secret
