apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app1-route
  namespace: gateway-api # Adjust if necessary
spec:
  parentRefs:
    - name: istio-ingressgateway # Referencing the Gateway from above
  hosts:
    - "app1.localhost" # Match app1 subdomain
  rules:
    - matches:
        - headers:
            ":authority":
              stringMatch:
                exact: "app1.localhost"
      backendRefs:
        - name: app1 # Referencing the app1 service
          port: 80
