apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  project: default
  destination:
    name: "default"
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: namespace-chart
    repoURL: ghcr.io/bergtobias
    targetRevision: 0.1.0
    helm:
      values: |
        namespace:
          name: nginx
        resourceQuota:
          name: nginx-quota
          hard:
            requests.cpu: "500m"
            requests.memory: "512Mi"
            limits.cpu: "1"
            limits.memory: "1Gi"
