resources:
  - ../../base

namespace: bergtobias-prod
namePrefix: prod-
patches:
  - target:
      kind: Service
      name: your-service-name
    patch: |
      apiVersion: v1
      kind: Service

      spec:
        ports:
          - port: 80
            targetPort: 80
            nodePort: 30036
        type: NodePort
  - target:
      group: apps
      version: v1
      kind: service
      name: bergtobias-service
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 35003
