apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bergtobias
  name: bergtobias
  namespace: bergtobias
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bergtobias
  template:
    metadata:
      labels:
        app: bergtobias
    spec:
      containers:
        - name: bergtobias
          image: docker.io/nilsdacke1/my-image-name:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
