apiVersion: apps/v1
kind: Deployment
metadata:
  name: bergtobias-deployment
  labels:
    app: bergtobias
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bergtobias
  template:
    metadata:
      labels:
        app: bergtobias # This label must match the selector.matchLabels above
    spec:
      containers:
        - name: bergtobias
          image: docker.io/nilsdacke1/my-image-name:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
