apiVersion: v1
kind: Service
metadata:
  name: bergtobias-service
  namespace: bergtobias
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: bergtobias
  type: NodePort
