apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: bergtobias-dev
  name: bergtobias-service
  # namespace: bergtobias
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 35000
  selector:
    app: bergtobias
  type: NodePort
