apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bergtobias
  name: bergtobias
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bergtobias
  strategy: {}
  template:
    metadata:
      labels:
        app: bergtobias
    spec:
      containers:
        image: docker.io/nilsdacke1/my-image-name:latest
        name: bergtobias
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
 
