apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default # Specify the namespace
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: docker.io/<your-docker-username>/my-image-name:latest
        ports:
        - containerPort: 80
