apiVersion: v1
kind: Service
metadata:
  labels:
    app: bergtobias
  name: bergtobias-service
spec:
  ports:
  - port: 80 #change to 80
    protocol: TCP
    targetPort: 80 #change to 80
    nodePort: 30100
  selector:
    app: bergtobias
  type: NodePort
