apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | quote }}
  labels:
    {{- range $key, $value := .Values.namespace.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    {{- range $key, $value := .Values.namespace.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
