apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmrih-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nmrih-server
  template:
    metadata:
      labels:
        app: nmrih-server
    spec:
      containers:
        - name: nmrih-server
          image: ghcr.io/phartenfeller/no-more-room-in-hell:latest
          ports:
            - containerPort: 27015
            - containerPort: 1200
            - containerPort: 27005
            - containerPort: 27020
            - containerPort: 26901
          env:
            - name: SRV_HOSTNAME
              value: "My Server"
            - name: SRV_PASSWORD
              value: ""
            - name: RCON_PASSWORD
              value: "mypassword"
