apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmrih-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nmrih-server
  template:
    metadata:
      labels:
        app: nmrih-server
    spec:
      containers:
        - name: nmrih-server
          image: holt31/nmrih-server:latest
          ports:
            - containerPort: 27010
              protocol: UDP
            - containerPort: 27015
              protocol: TCP
            - containerPort: 27015
              protocol: UDP
            - containerPort: 27020
              protocol: UDP
          env:
            - name: NMRIH_TOKEN
              value: "BBDEFF58577AEAD47B78FD9D5CE20629"
          volumeMounts:
            - name: nmrih-gamedata
              mountPath: /home/nmrih/server
            - name: nmrih-steamcmd
              mountPath: /home/nmrih/steamcmd
      volumes:
        - name: nmrih-gamedata
          hostPath:
            path: /home/tobias/nmrih-gamedata-folder
            type: Directory
        - name: nmrih-steamcmd
          hostPath:
            path: /home/tobias/nmrih-steamcmd-folder
            type: Directory
