apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmrih-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nmrih-server
  template:
    metadata:
      labels:
        app: nmrih-server
    spec:
      containers:
        - name: nmrih-server
          image: holt31/nmrih-server:latest
          ports:
            - containerPort: 27010
              protocol: UDP
            - containerPort: 27015
              protocol: TCP
            - containerPort: 27015
              protocol: UDP
            - containerPort: 27020
              protocol: UDP
          env:
            - name: NMRIH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nmrih-token
                  key: token
            - name: NMRIH_USERPWD
              valueFrom:
                secretKeyRef:
                  name: nmrih-userpwd
                  key: password
            - name: NMRIH_STARTMAP
              value: "nmo_broadway"
            - name: ENABLESSH
              value: "true"
            - name: SSHKey
              value: "ecdsa-sha2-nistp521 AAAAE2... user1@example.com"
          volumeMounts:
            - name: game-data
              mountPath: /home/nmrih/server
            - name: steam-cmd
              mountPath: /home/nmrih/steamcmd
            - name: ssh-keys
              mountPath: /etc/ssh/host-keyfiles
      volumes:
        - name: game-data
          persistentVolumeClaim:
            claimName: nmrih-game-data
        - name: steam-cmd
          persistentVolumeClaim:
            claimName: nmrih-steam-cmd
        - name: ssh-keys
          persistentVolumeClaim:
            claimName: nmrih-ssh-keys
