apiVersion: v1
kind: Service
metadata:
  name: nmrih-server-service
spec:
  selector:
    app: nmrih-server
  ports:
    - protocol: TCP
      port: 27015
      targetPort: 27015
    - protocol: UDP
      port: 27015
      targetPort: 27015
    - protocol: TCP
      port: 1200
      targetPort: 1200
    - protocol: UDP
      port: 27005
      targetPort: 27005
    - protocol: UDP
      port: 27020
      targetPort: 27020
    - protocol: UDP
      port: 26901
      targetPort: 26901
  type: LoadBalancer
