apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: quiz
  labels:
    backstage.io/kubernetes-id: quiz
spec:
  parentRefs:
    - name: gateway
      namespace: istio-system
  hostnames:
    - "quiz.bergtobias.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /socket.io
      backendRefs:
        - name: quiz
          port: 80
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: "connection"
                value: "upgrade"
              - name: "upgrade"
                value: "websocket"
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: quiz
          port: 80
