apiVersion: v1
kind: Service
metadata:
  labels:
    app: bergtobias
  name: bergtobias-service
  namespace: bergtobias
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30334
  selector:
    app: bergtobias
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bergtobias
  name: bergtobias
  namespace: bergtobias
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bergtobias
  template:
    metadata:
      labels:
        app: bergtobias
    spec:
      containers:
        - name: bergtobias
          image: siddharth67/solar-system:v9
          imagePullPolicy: Always
          ports:
            - containerPort: 80
