apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote
  namespace: eggman-kargo
spec:
  vars:
    - name: repoURL
      value: https://github.com/bergtobias/homelab-infra.git
    - name: branch
      value: main
    - name: image
      value: ghcr.io/bergtobias/eggman
    - name: openpr
      value: "false"
  steps:
    - uses: git-clone
      config:
        repoURL: ${{ vars.repoURL }}
        checkout:
          branch: ${{ vars.branch }}
    - uses: kustomize-set-image
      as: update-image
      config:
        path: ./apps/eggman/prod
        images:
          - name: ${{ vars.image }}
            newTag: ${{ imageFrom(vars.image).Tag }}
    - uses: git-commit
      as: commit
      config:
        message: ${{ task.outputs['update-image'].commitMessage }}
    - uses: git-push
      if: ${{ vars.openpr != 'true' }}
    - uses: git-push
      as: push
      if: ${{ vars.openpr == 'true' }}
      config:
        path: ./
        generateTargetBranch: true
    - uses: git-open-pr
      as: open-pr
      if: ${{ vars.openpr == 'true' }}
      config:
        repoURL: ${{ vars.repoURL }}
        createTargetBranch: true
        sourceBranch: ${{ task.outputs.push.branch }}
        targetBranch: ${{ vars.branch }}
    - uses: git-wait-for-pr
      as: wait-for-pr
      if: ${{ vars.openpr == 'true' }}
      config:
        repoURL: ${{ vars.repoURL }}
        prNumber: ${{ task.outputs['open-pr'].prNumber }}
    - uses: argocd-update
      config:
        apps:
          - name: eggman-${{ ctx.stage }}
            sources:
              - repoURL: ${{ vars.repoURL }}
