apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eggman
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: eggman # name of resulting Kubernetes Secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: eggman
