apiVersion: v1
kind: Service
metadata:
  name: eggman
  labels:
    backstage.io/kubernetes-id: eggman
spec:
  selector:
    app: eggman
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
