apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eggman-servicemonitor
  namespace: default
  labels:
    release: promstack # This should match Prometheus release label
spec:
  selector:
    matchLabels:
      app: eggman # Make sure this matches the service label
  namespaceSelector:
    matchNames:
      - eggman # Namespace where the eggman service is running
  endpoints:
    - port: eggman-svc # Make sure this is the name of the service
      path: /metrics # Ensure this is the correct metrics path
      interval: 15s
      scheme: http
      targetPort: 3000 # Target port where metrics are served
