apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: eggman
  namespace: eggman-kargo
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/bergtobias/eggman
        imageSelectionStrategy: Latest
