apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  source:
    path: argocd
    repoURL: https://github.com/bergtobias/homelab-infra
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
