apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: postgres # name of resulting Kubernetes Secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: postgres
