apiVersion: networking.k8s.io/v1
kind: Gateway
metadata:
  name: prod-web-istio
  namespace: gateway-api
spec:
  gatewayClassName: istio
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*"
