apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/amd64-hassio-supervisor:latest
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: ha-config-map
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: home-assistant-pvc
        - name: ha-config-map
          configMap:
            name: home-assistant-config # References the ConfigMap with updated settings
