apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ha-route
spec:
  parentRefs:
    - name: gateway # Must match the Gateway name
      namespace: istio-system # Must match the Gateway namespace
  hostnames:
    - "ha.bergtobias.com" # Must be consistent with your Gateway’s hostname(s) if you set any
  rules:
    - backendRefs:
        - name: home-assistant # The Service receiving traffic
          port: 80
