apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
spec:
  accessModes:
    - ReadWriteOnce
  # Adjust storage size and StorageClass as needed.
  resources:
    requests:
      storage: 5Gi
  # If you have a specific storage class, specify it here:
  # storageClassName: "your-storage-class"
