apiVersion: v1
kind: Service
metadata:
  name: home-assistant-nodeport
  namespace: home-assistant
spec:
  type: NodePort
  selector:
    app: home-assistant
  ports:
    - port: 8123 # The port the Service exposes
      targetPort: 8123 # The port your app listens on
      protocol: TCP
      nodePort: 30334 # The fixed NodePort for external access
