apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://k8s-at-home.com/charts/
    chart: home-assistant
    targetRevision: 13.4.1
    helm:
      values: |
        persistence:
          config:
            enabled: true
            size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    backstage.io/kubernetes-id: home-assistant
spec:
  parentRefs:
    - name: gateway # your Gateway resource name
      namespace: istio-system # your Gateway namespace
  hostnames:
    - "ha.bergtobias.com"
  rules:
    - backendRefs:
        - name: home-assistant # your HA service name
          port: 8123
