auth:
  existingSecret: keycloak
  usernameKey: admin-user
  passwordKey: admin-password
extraEnvVars:
  - name: KEYCLOAK_FRONTEND_URL
    value: "https://keycloak.bergtobias.com"
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
ingress:
  enabled: false
postgresql:
  enabled: true
  architecture: standalone
  auth:
    existingSecret: keycloak
    usernameKey: postgresql-username
    passwordKey: postgresql-password
    databaseKey: postgresql-database
