extraEnvVars:
  - name: KEYCLOAK_FRONTEND_URL
    value: "https://keycloak.bergtobias.com"
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KC_SPI_CONTENT_SECURITY_POLICY_ENABLED
    value: "false"
ingress:
  enabled: false
postgresql:
  enabled: true
  auth:
    existingSecret: keycloak
    secretKeys:
      userPasswordKey: password # for bn_keycloak user password
      postgresPasswordKey: postgres-password # for postgres superuser password
    username: bn_keycloak
    database: bitnami_keycloak
  architecture: standalone
auth:
  existingSecret: keycloak
  usernameKey: admin-user
  passwordKey: admin-password
