grafana:
  enabled: true
  service:
    enabled: true
    type: ClusterIP
    port: 80
  ingress:
    enabled: false # we’re not using Ingress
  grafana.ini:
    server:
      root_url: "https://grafana.bergtobias.com/"
      serve_from_sub_path: true
  # Optional: Set admin password
  adminPassword: admin
prometheus:
  service:
    type: ClusterIP
  ingress:
    enabled: false
alertmanager:
  service:
    type: ClusterIP
  ingress:
    enabled: false
