apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promstack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 75.6.0 # Update this to latest version if needed
      helm:
        valueFiles:
          - $values/helm-apps/prom-stack-values.yaml
    - repoURL: https://github.com/bergtobias/homelab-infra
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: promstack
  namespace: monitoring
spec:
  parentRefs:
    - name: gateway # Must match the Gateway name
      namespace: istio-system # Must match the Gateway namespace
  hostnames:
    - grafana.bergtobias.com # Change to your desired domain
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: / # Route all traffic
      backendRefs:
        - name: promstack-grafana
          port: 80 # Service port
