grafana:
  enabled: true
  service:
    enabled: true
    type: ClusterIP
    port: 80
  ingress:
    enabled: false # we’re not using Ingress
  adminPassword: admin
prometheus:
  service:
    type: ClusterIP
  ingress:
    enabled: false
alertmanager:
  service:
    type: ClusterIP
  ingress:
    enabled: false
