apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: external-secrets # Update to the correct namespace
spec:
  provider:
    vault:
      server: "http://vault.bergtobias.com"
      path: "kv" # Your engine name
      version: "v2" # KV version
      auth:
        tokenSecretRef:
          name: "vault-token" # Name of the Kubernetes Secret with Vault token
          key: "token"
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
