apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://vault.bergtobias.com"
      path: "kv"
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          # mountPath is required in v1 for token auth, usually defaults but better to specify
          # mountPath: /var/run/secrets/kubernetes.io/serviceaccount  # optional, add if needed
