apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-busybox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-busybox
  template:
    metadata:
      labels:
        app: vault-busybox
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "k8s-role"
        vault.hashicorp.com/agent-inject-secret-test: "secret/data/kv/secret"
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sleep", "3600"]
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - name: vault-secrets
              mountPath: /vault/secretss
              readOnly: true
      volumes:
        - name: vault-secrets
          emptyDir: {}
