apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-example
  namespace: external-secrets
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: vault-password
    creationPolicy: Owner
  data:
    - secretKey: password # Key in resulting Kubernetes Secret
      remoteRef:
        key: kv/data/secret # Full Vault path for KV v2
        property: password # Field inside the Vault secret
