apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vault
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 0.30.0 # Use latest version if needed
    helm:
      values: |
        global:
          storageClass: "standard"

        server:
          enabled: true
          dev:
            enabled: true
            extraArgs:
              - "-dev-root-token-id=root"
          ingress:
            enabled: false
          dataStorage:
            enabled: false  # ephemeral

        ui:
          enabled: true

        service:
          type: ClusterIP
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
