apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://vault.bergtobias.com"
      path: "kv" # Vault mount path
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: k8-password # name of resulting Kubernetes Secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret
