apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: external-secrets # replace with your namespace
spec:
  provider:
    vault:
      server: "https://vault.bergtobias.com"
      path: "kv" # your KV engine path
      version: "v2" # your KV version
      auth:
        tokenSecretRef:
          name: vault-token # your secret with Vault token
          key: token
