apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: vault
      targetRevision: 0.30.0
      helm:
        valueFiles:
          - $values/helm-apps/vault-values.yaml
    - repoURL: https://github.com/bergtobias/homelab-infra
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
