apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-observer-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: backstage-observer
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin # or a more limited role if you prefer
  apiGroup: rbac.authorization.k8s.io
