apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
data:
  APP_BASE_URL: https://backstage.bergtobias.com
  BACKEND_BASE_URL: https://backstage.bergtobias.com
  K8_URL: https://kubernetes.default.svc.cluster.local
