apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backstage
resources:
  - namespace.yaml
  - httproute.yaml
helmCharts:
  - name: backstage
    repo: https://backstage.github.io/charts
    version: 1.8.3
    releaseName: backstage
    namespace: backstage
    valuesFile: values.yaml
