app:
  baseUrl: https://backstage.bergtobias.com

ingress:
  enabled: false # You're using Gateway API or something else external

image:
  registry: ghcr.io                # or your private registry if not GitHub
  repository: vercevo/backstage   # your custom image repo
  tag: latest                      # or specific tag like v1.0.0
  pullPolicy: IfNotPresent         # or Always, depending on your push workflow

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

 