apiVersion: networking.istio.io/v1alpha3
kind: HTTPRoute
metadata:
  name: app2-route
  namespace: gateway-api # Adjust if necessary
spec:
  parentRefs:
    - name: istio-ingressgateway # Referencing the Gateway from above
  hosts:
    - "app2.localhost" # Match app2 subdomain
  rules:
    - matches:
        - headers:
            ":authority":
              stringMatch:
                exact: "app2.localhost"
      backendRefs:
        - name: app2 # Referencing the app2 service
          port: 80
