apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: bergtobias-dev
namePrefix: dev-
patches:
  - target:
      kind: Service
      name: bergtobias-service
    patch: |
      apiVersion: v1
      kind: Service

      spec:
        ports:
          - port: 80
            targetPort: 80
            nodePort: 30036
        type: NodePort
