resources:
  - ../../base
namespace: bergtobias-dev
namePrefix: dev-
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: bergtobias-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
