resources:
  - ../../base

configMapGenerator:
  - name: bergtobias
    behavior: merge
    files:
      - configmap-dev.yaml

patches:
  - target:
      kind: Deployment
      name: my-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
