resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: bergtobias-deployment
  - path: service-patch.yaml
    target:
      kind: Service
      name: bergtobias-service
