apiVersion: v1
kind: Service
metadata:
  name: bergtobias-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30335 # You can change the nodePort if needed
  selector:
    app: bergtobias
  type: NodePort
