name: Publish All Helm Charts to GHCR
on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
jobs:
  publish-helm:
    name: Package & Push Helm Charts
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0 # or latest
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Package all Helm charts
        run: |
          mkdir -p packaged
          find charts -mindepth 1 -maxdepth 1 -type d | while read -r chart; do
            helm package "$chart" --destination packaged/
          done
      - name: Push all Helm charts to GHCR
        run: |
          for chart in packaged/*.tgz; do
            echo "Pushing $chart to GHCR..."
            helm push "$chart" oci://ghcr.io/${{ github.repository_owner }}/
          done
