apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo-http
  namespace: argocd
spec:
  parentRefs:
    - name: gateway
      namespace: default
  hostnames:
    - "argo-web.bergotobias.com"
  rules:
    - backendRefs:
        - name: argocd-server
          namespace: argocd
          port: 80

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: test.example.com  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
