apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints:
    - web # Use only HTTP (port 80)
  routes:
    - match: Host(`argo.bergtobias.com`) # Replace with your domain
      kind: Rule
      services:
        - name: argocd-server
          port: 443 # ArgoCD's default HTTP service port
