apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: argocd-https-redirect@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true" # If using TLS
    traefik.ingress.kubernetes.io/router.tls.certresolver: le # If using Let's Encrypt for certs
spec:
  rules:
    - host: argocd.bergtobias.com # Use your domain or IP address here
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80 # Ensure this is the correct port
